server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/OscarLuque-31/ghost-follow
          search-paths: config-files/
          default-label: main
          clone-on-start: true
          timeout: 5